# Header
menu:
  Home: /
  JAVA: /categories/java/
  PHP: /categories/php
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: true

# Sidebar
sidebar: right
widgets:
  - recent_posts
  - category
  #- tag
  #- link
  - tagcloud
#- archive

# widget behavior
archive_type: 'monthy'
archive_format: 'YYYY/MM'
show_count: false

# Miscellaneous
favicon:
logo_text: ""
logo_img: "images/logo.svg"
show_author: false
allow_search: true

# Comments
allow_comment: false
gitalk:
  cdnCssUrl: https://unpkg.com/gitalk@latest/dist/gitalk.css
  cdnJsUrl: https://unpkg.com/gitalk@latest/dist/gitalk.min.js
  clientID:
  clientSecret:
  repo:
  owner:
  admin:
  distractionFreeMode: false
  language: en
  perPage: 10

# Links
links:
  Baidu: https://www.baidu.com/

# Code block copy btn
allow_code_copy: true

